### ISSUE TITLE
bitbucket R Package clone addLocalPackage bug

### ISSUE THREAD

**Issue by matthias-da** [andrie/miniCRAN#116]
Dear Andrie and Alex,

First, thanks for the wonderful miniCRAN package.

I think there is one bug with addLocalPackage.
When cloning a bitbucket repository (which contains an R package), addLocalPackage produces the error 

Error in strsplit(f, "_") : non-character argument

This happens in function .listFiles, more precisely in 

```{r}
fp <- local({
      x <- strsplit(f, "_")
      sapply(x, `[[`, 1)
})
```

because f looks like (indpendently which bitbucket R Package you choose

```{r}
str(f)
```

List of 1
 $ packagename: chr(0) 

Currently it seems whenever a R package is hosted on bitbucket, addLocalPackage will not work.

If you have any ideas how to solve this bug, I would be more than happy.

Kind regards,
Matthias

**Comment by achubaty** [comment]
I haven't used BitBucket, but a quick google got me poking around the structure of BitBucket repos. A couple things to note:

1. It looks like the package is a subdirectory of the repo itself, so you'll need to make sure you pass the correct path to `addLocalPackage()`;
2. The source code itself needs to be build as a package in order to be able to add in to the miniCRAN repo.

The following works for the [polygonlandscapemetrics](https://bitbucket.org/cmbce/r-package-polygonlandscapemetrics) package, which I previously cloned to my machine:

```r
> library(miniCRAN)
> tmpdir <- file.path(tempdir(), "miniCRAN")
> dir.create(tmpdir)
> makeRepo(pkgDep("devtools"), path = tmpdir)
> addLocalPackage(path = tmpdir, pkgs = "polygonLandscapeMetrics", pkgPath = "~/GitHub/r-package-polygonlandscapemetrics", build = TRUE)
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD build  \
  '/home/achubaty/Documents/GitHub/r-package-polygonlandscapemetrics/polygonLandscapeMetrics'  \
  --no-resave-data --no-manual 

* checking for file ‘/home/achubaty/Documents/GitHub/r-package-polygonlandscapemetrics/polygonLandscapeMetrics/DESCRIPTION’ ... OK
* preparing ‘polygonLandscapeMetrics’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* looking to see if a ‘data/datalist’ file should be added
* building ‘polygonLandscapeMetrics_0.0.0.9000.tar.gz’

copying polygonLandscapeMetrics_0.0.0.9000.tar.gz

Warning message:
In addLocalPackage(path = tmpdir, pkgs = "polygonLandscapeMetrics",  :
  Building local packages is still being tested.
```

However, do note that I get your error when I forget to pass `build = TRUE`:

```r
> addLocalPackage(path = tmpdir, pkgs = "polygonLandscapeMetrics", pkgPath = "~/GitHub/r-package-polygonlandscapemetrics")
Error in strsplit(f, "_") : non-character argument
```

**Comment by matthias-da** [comment]
simple perfect. This works. Such a simple solution that can be easliy overseen. Your explanation makes sense. Thanks again.
