### ISSUE TITLE
Remove dependency on XML

### ISSUE THREAD

**Issue by andrie** [andrie/miniCRAN#75]
In favour of `xml2`.

`xml2` is smaller, faster, has fewer bugs and doesn't have an external system dependency.

**Comment by achubaty** [comment]
**NOTE:** [`xml2`](https://cran.r-project.org/web/packages/xml2/index.html) does have external system dependencies 

 > SystemRequirements:	libxml2: libxml2-dev (deb), libxml2-devel (rpm)

**Comment by jangorecki** [comment]
@achubaty `XML` also have OS dep. I see in NAMESPACE that it `import(XML)` so hard to track what is actually used from `XML` package. Personally I would aim to drop both deps if possible.

**Comment by nuest** [comment]
I recently made the switch from `XML` to `xml2` for a package with a lot of XML parsing and creation, see [this issue](https://github.com/52North/sos4R/issues/42) and the referenced commits. I took some notes on the process and lessons I learned, it might be helpful for your issue here if you decide to keep an xml library dependency: https://gist.github.com/nuest/3ed3b0057713eb4f4d75d11bb62f2d66

**Comment by andrie** [comment]
The `XML` package is only used by the `getCranDescription()` function, and only for versions of R prior to 3.4.0.

I am now adding a warning to this function if you run this in R <= 3.4.0, so we can remove this functionality in a future release.

Action:

- [ ] Remove XML completely early 2020
- [ ] Throw error on `getCranDescription()` if R <= 3.4.0

**Comment by andrie** [comment]
The most recent version of XML has a dependency on R-4.0 so I'm removing XML altogether in the next release.
